FROM rust:latest

# configure users
ARG MNT_PATH
ARG PASS
ARG USER_ID
ARG USER_NAME
ARG GROUP_ID
ARG GROUP_NAME
ARG DOCKER_GROUP_ID

RUN addgroup -gid $DOCKER_GROUP_ID docker && \
    if [ $USER_NAME != 'root' ]; then \
    groupadd --gid ${GROUP_ID} ${GROUP_NAME}; \
    useradd --no-log-init --create-home --shell /bin/bash --uid ${USER_ID} --gid ${GROUP_ID} ${USER_NAME}; \
    fi && \
    usermod -a -G docker $USER_NAME && \
    usermod -a -G sudo $USER_NAME && \
    echo "$USER_NAME:$PASS" | chpasswd && \
    echo "root:$PASS" | chpasswd

WORKDIR /tmp

# install sudo
RUN apt-get update && apt-get -y install sudo netcat

# install docker
RUN apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install docker-ce docker-ce-cli containerd.io -y

#install docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

#install rust tools
RUN rustup component add rustfmt && \
    cargo install cargo-modules cargo-audit cargo-tarpaulin cargo-nextest cargo-make cargo-release cargo-watch cargo-edit

#install bash tools
RUN apt install -y protobuf-compiler nano

WORKDIR $MNT_PATH

USER $USER_NAME

CMD ["sleep", "infinity"]
